### ISSUE TITLE
Exception on start

### ISSUE THREAD

**Issue by puerstiOVUM** [thedevtalkshow/BlazorAuthFromScratch#2]
System.ArgumentException: The 'ClientId' option must be provided. (Parameter 'ClientId')
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions.Validate()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
   at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by SpaceShot** [comment]
This occurs if there is no configuration set for the secrets and settings for Google or Microsoft Authentication.

The sample app sets up external authentication with a Google Account and provides for single tenant authentication with Microsoft Entra ID.

We didn't show the actual secrets on the show, but an example secrets.json looks like the following, except that you paste in the secrets and settings for your own Google registration and/or your own EntraID App Registration

``` json
{
  "Authentication": {
    "Google": {
      "ClientId": "<your client id>",
      "ClientSecret": "<your client secret>"
    },
    "Microsoft": {
      "ClientId": "<your client id>",
      "ClientSecret": "<your client secret>",
      "TokenEndpoint": "https://login.microsoftonline.com/<your-tenant-id>/oauth2/v2.0/token",
      "AuthorizationEndpoint": "https://login.microsoftonline.com/<your-tenant-id>/oauth2/v2.0/authorize"
    }
  }
}
```

You don't have to use secrets.json but you do have to set this configuration according to your preference.  Our recommendation is not to put this in appsettings.json so that you don't accidentally commit to source control.
